memory_limit = 512M
max_execution_time = 120

date.timezone = UTC

expose_php = Off

opcache.enable = 1
opcache.enable_cli = 1
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0

pcov.enabled = 1
pcov.directory = /var/www/html/app
pcov.initial.memory = 33554432
